name: GitHub Actions

# only run this workflow on new commits to main
# or PRs into main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    # Run every Monday morning at 11:00a UTC, 6:00a CST
    - cron: '0 11 * * 1'

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: linting
            name: linting
            python_version: 3.7
          - task: sdist
            name: sdist
            python_version: 3.7
          - task: unit-tests
            prefect_version: ">0.13.0,<0.14.0"
            ruamel_yaml_version: "==0.16.0"
            name: "unit-tests (prefect 0.13.x, ruamel.yaml 0.16.0, Python 3.7)"
            python_version: 3.7
          - task: unit-tests
            prefect_version: ">0.14.0,<0.15.0"
            ruamel_yaml_version: ">=0.17.7"
            name: "unit-tests (prefect 0.14.x, ruamel.yaml latest, Python 3.7)"
            python_version: 3.7
          - task: unit-tests
            prefect_version: ""
            ruamel_yaml_version: ">=0.17.7"
            name: "unit-tests (prefect latest, ruamel.yaml latest, Python 3.8)"
            python_version: 3.8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: linting
        if: matrix.task == 'linting'
        shell: bash
        run: |
          pip install --upgrade black flake8 mypy pylint
          make lint
      - name: unit-tests
        if: matrix.task == 'unit-tests'
        shell: bash
        run: |
          pip install -I --upgrade -e .[test]
          pip install -I --upgrade 'ruamel.yaml${{ matrix.ruamel_yaml_version }}'
          make unit-tests
      - name: test source distribution
        if: matrix.task == 'sdist'
        shell: bash
        run: |
          pip install 'prefect${{ matrix.prefect_version }}'
          python setup.py sdist
          pip install dist/prefect-saturn-$(cat VERSION).tar.gz
  # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: note that all tests succeeded
      run: echo "all tests succeeded"
